name: circle_bottombar
description: Animation circle bottom bar.
version: 1.0.0
author: Mehran Jafari  <mehran.flutter@gmail.com>
homepage: https://github.com/mehrtarh/animation_circle_bottom_bar


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6


flutter:
