name: startapp_flutter
description: Admob plugin that shows banner ads using native platform views.
version: 0.1.0
author: Mehran Jafari  <mehran.flutter@gmail.com>
homepage: https://github.com/mehrtarh/animation_circle_bottom_bar


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6


flutter:
